#########################################################
# Receiver service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
spec:
  selector:
    matchLabels:
      app: receiver
  replicas: 1
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: andreadelligatti/receiver
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: common-env
        - configMapRef:
            name: host-env
        env:
          - name: SERVICES
            value: receiver